# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'example3' do
  workspace 'example3'

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for example3

  target 'example3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'example3UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
